export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST"
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS"
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL"

export const GET_ALL_PROJECTS_REQUEST = "GET_ALL_PROJECTS_REQUEST"
export const GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS"
export const GET_ALL_PROJECTS_FAIL = "GET_ALL_PROJECTS_FAIL"

export const GET_ALL_USERS_IN_PROJECT_REQUEST = "GET_ALL_USERS_IN_PROJECT_REQUEST"
export const GET_ALL_USERS_IN_PROJECT_SUCCESS = "GET_ALL_USERS_IN_PROJECT_SUCCESS"
export const GET_ALL_USERS_IN_PROJECT_FAIL = "GET_ALL_USERS_IN_PROJECT_FAIL"

export const ADD_USER_TO_PROJECT_REQUEST = "ADD_USER_TO_PROJECT_REQUEST"
export const ADD_USER_TO_PROJECT_SUCCESS = "ADD_USER_TO_PROJECT_SUCCESS"
export const ADD_USER_TO_PROJECT_FAIL = "ADD_USER_TO_PROJECT_FAIL"
